/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package outputdeadlock.plugin;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

public class OutputDeadlockPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("outputDeadlock", OutputDeadlockTask.class);
    }
}
